// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CAATest5
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Feb 2016  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Public);
AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("Dialog",Public);
// END WIZARD EDITION ZONE
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("DraftingInterfaces",Public);

AddPrereqComponent("Mathematics",Public);
