// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CAATest1
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2016  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Public);
// END WIZARD EDITION ZONE
AddPrereqComponent("Dialog",Public);
