// COPYRIGHT Dassault Systemes 2016
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework CAATest3
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2016  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Public);
// END WIZARD EDITION ZONE
AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("DraftingInterfaces",Public);
AddPrereqComponent("DialogEngine",Public);
AddPrereqComponent("CATSketcherUseItf",Public);
AddPrereqComponent("Visualization",Public);
AddPrereqComponent("VisualizationBase",Public);
AddPrereqComponent("PartInterfaces",Public);
AddPrereqComponent("SketcherUI",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
