# COPYRIGHT Dassault Systemes 2016
#======================================================================
# Imakefile for module TSConsole.m
#======================================================================
#
#  Oct 2016  Creation: Code generated by the CAA wizard  Administrator
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP
# END WIZARD EDITION ZONE

LINK_WITH =JS0GROUP \
 CPPOpenNurbs \

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
