# COPYRIGHT Dassault Systemes 2016
#======================================================================
# Imakefile for module DrwConsole.m
#======================================================================
#
#  Feb 2016  Creation: Code generated by the CAA wizard  Administrator
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP
# END WIZARD EDITION ZONE

LINK_WITH = JS0CORBA \
			CATObjectModelerBase \
            CATObjectSpecsModeler \
            CATDraftingInterfaces \
           

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
